[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

solc = "0.8.25"

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/'
]
